definitions:
  models.Currency:
    properties:
      adate:
        type: string
      code:
        type: string
      id:
        type: integer
      title:
        type: string
      value:
        type: number
    type: object
info:
  contact: {}
paths: {}
swagger: "2.0"
